name: Build and Push Hop v2 Explorer Backend Docker Image

on:
  push:
    branches:
      - v2-explorer-backend-production
      - v2-explorer-backend-goerli
      - v2-explorer-backend-sepolia

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      branch_name: ${{ steps.extract_branch.outputs.branch }}
    steps:
      - name: Extract branch name
        id: extract_branch
        run: echo "::set-output name=branch::${GITHUB_REF##*/}"

  build-v2-explorer-backend:
    runs-on: ubuntu-latest
    environment: docker
    env:
      DOCKER_IMAGE: hopprotocol/v2-explorer-backend
    defaults:
      run:
        working-directory: .
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build application Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./packages/v2-explorer-backend/Dockerfile
          build-args: GIT_REV=${{ github.sha }}
          tags: app
          load: true
          push: false

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Push v2 Explorer Backend Docker image to Docker Hub
        run: |
          BRANCH=${GITHUB_REF##*/}
          BRANCH=$(echo $BRANCH | sed 's/\//-/g' | sed 's/v2-explorer-backend-//g')
          docker tag app $DOCKER_IMAGE:${{ github.sha }}
          docker tag app $DOCKER_IMAGE:$BRANCH
          docker push $DOCKER_IMAGE:${{ github.sha }}
          docker push $DOCKER_IMAGE:$BRANCH
          if [ "$BRANCH" == "production" ]; then
            docker tag app $DOCKER_IMAGE:latest
            docker push $DOCKER_IMAGE:latest
          fi

